source "https://rubygems.org"
ruby RUBY_VERSION

gem "jekyll", "3.2.1"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  # gem "jekyll-github-metadata", "~> 1.0"
  gem 'bootstrap', '~> 4.0.0.alpha3'
  gem 'autoprefixer-rails'
  gem 'jekyll-assets'
end
